package com.sange.tacz_bsb;

import com.sange.tacz_bsb.item.GlintMaterialItem;
import com.sange.tacz_bsb.item.GlintAssemblyItem;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/** Generated by tools/generate_precise_recipes.py against the pinned Create TaCZ release. */
public final class BsbMaterials {
    private static final Map<String, DeferredItem<? extends Item>> REGISTERED = new LinkedHashMap<>();
    public static final Map<String, DeferredItem<? extends Item>> ITEMS = Collections.unmodifiableMap(REGISTERED);
    static {
        add("high_gunpowder_cake");
        add("high_gunpowder_cake_dry");
        add("high_gunpowder_cylinder");
        add("high_gunpowder_charge");
        add("high_gunpowder_pellets");
        add("high_gunpowder_grains");
        add("high_explosive");
        add("hardened_bullet");
        add("hardened_large_bullet");
        add("hardened_pellets");
        add("precise_rpg_warhead");
        add("precise_rpg_sustainer_motor");
        add("precise_rpg_booster_charge");
        add("precise_explosive_charge_40mm");
        add("precise_fuse_40mm");
        add("precise_fuseless_40mm");
        add("high_casefull_12g");
        add("unfinished_high_casefull_12g");
        add("unfinished_precise_12g");
        add("high_casefull_22wmr");
        add("unfinished_high_casefull_22wmr");
        add("unfinished_precise_22wmr");
        add("high_casefull_3006");
        add("unfinished_high_casefull_3006");
        add("unfinished_precise_3006");
        add("high_casefull_308");
        add("unfinished_high_casefull_308");
        add("unfinished_precise_308");
        add("high_casefull_338");
        add("unfinished_high_casefull_338");
        add("unfinished_precise_338");
        add("high_casefull_357mag");
        add("unfinished_high_casefull_357mag");
        add("unfinished_precise_357mag");
        add("high_casefull_4570");
        add("unfinished_high_casefull_4570");
        add("unfinished_precise_4570");
        add("high_casefull_45acp");
        add("unfinished_high_casefull_45acp");
        add("unfinished_precise_45acp");
        add("high_casefull_4630");
        add("unfinished_high_casefull_4630");
        add("unfinished_precise_4630");
        add("high_casefull_500mag");
        add("unfinished_high_casefull_500mag");
        add("unfinished_precise_500mag");
        add("high_casefull_50ae");
        add("unfinished_high_casefull_50ae");
        add("unfinished_precise_50ae");
        add("high_casefull_50bmg");
        add("unfinished_high_casefull_50bmg");
        add("unfinished_precise_50bmg");
        add("high_casefull_54539");
        add("unfinished_high_casefull_54539");
        add("unfinished_precise_54539");
        add("high_casefull_55645");
        add("unfinished_high_casefull_55645");
        add("unfinished_precise_55645");
        add("high_casefull_5728");
        add("unfinished_high_casefull_5728");
        add("unfinished_precise_5728");
        add("high_casefull_5842");
        add("unfinished_high_casefull_5842");
        add("unfinished_precise_5842");
        add("high_casefull_6851fury");
        add("unfinished_high_casefull_6851fury");
        add("unfinished_precise_6851fury");
        add("high_casefull_76225");
        add("unfinished_high_casefull_76225");
        add("unfinished_precise_76225");
        add("high_casefull_76239");
        add("unfinished_high_casefull_76239");
        add("unfinished_precise_76239");
        add("high_casefull_76254");
        add("unfinished_high_casefull_76254");
        add("unfinished_precise_76254");
        add("high_casefull_792x57");
        add("unfinished_high_casefull_792x57");
        add("unfinished_precise_792x57");
        add("high_casefull_9mm");
        add("unfinished_high_casefull_9mm");
        add("unfinished_precise_9mm");
        add("unfinished_precise_fuseless_40mm");
        add("unfinished_precise_rpg_rocket");
        add("unfinished_precise_40mm");
    }
    private static void add(String name) {
        REGISTERED.put(name, name.startsWith("unfinished_")
                ? BsbContent.ITEMS.register(name, GlintAssemblyItem::new)
                : BsbContent.ITEMS.register(name, GlintMaterialItem::new));
    }
    public static void initialize() { /* Trigger registration before attaching the item register to the bus. */ }
}
